using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TP_DSYNC.Models.DataDefine.B3
{
    public class MSPCALARS
    {
        public int AUTOID { get; set; }
        public DateTime? DATETIME { get; set; }
        public Single? ASEF09_PAAC01 { get; set; }
        public Single? ASEF10_PAAC01 { get; set; }
        public Single? ASEF11_PAAC01 { get; set; }
        public Single? ASEF12_PAAC01 { get; set; }
        public Single? ASEF13_PAAC01 { get; set; }
        public Single? ASEF14_PAAC01 { get; set; }
        public Single? ASEF15_PAAC01 { get; set; }
        public Single? ASEF09_PAAC02 { get; set; }
        public Single? ASEF10_PAAC02 { get; set; }
        public Single? ASEF11_PAAC02 { get; set; }
        public Single? ASEF12_PAAC02 { get; set; }
        public Single? ASEF13_PAAC02 { get; set; }
        public Single? ASEF14_PAAC02 { get; set; }
        public Single? ASEF15_PAAC02 { get; set; }
        public Single? ASEF09_PAAC03 { get; set; }
        public Single? ASEF10_PAAC03 { get; set; }
        public Single? ASEF11_PAAC03 { get; set; }
        public Single? ASEF12_PAAC03 { get; set; }
        public Single? ASEF13_PAAC03 { get; set; }
        public Single? ASEF14_PAAC03 { get; set; }
        public Single? ASEF15_PAAC03 { get; set; }
        public Single? ASEF09_PAAC04 { get; set; }
        public Single? ASEF10_PAAC04 { get; set; }
        public Single? ASEF11_PAAC04 { get; set; }
        public Single? ASEF12_PAAC04 { get; set; }
        public Single? ASEF13_PAAC04 { get; set; }
        public Single? ASEF14_PAAC04 { get; set; }
        public Single? ASEF15_PAAC04 { get; set; }
        public Single? ASEF09_PAAC05 { get; set; }
        public Single? ASEF10_PAAC05 { get; set; }
        public Single? ASEF11_PAAC05 { get; set; }
        public Single? ASEF12_PAAC05 { get; set; }
        public Single? ASEF13_PAAC05 { get; set; }
        public Single? ASEF14_PAAC05 { get; set; }
        public Single? ASEF15_PAAC05 { get; set; }
        public Single? ASEF09_PAAC06 { get; set; }
        public Single? ASEF10_PAAC06 { get; set; }
        public Single? ASEF11_PAAC06 { get; set; }
        public Single? ASEF12_PAAC06 { get; set; }
        public Single? ASEF13_PAAC06 { get; set; }
        public Single? ASEF14_PAAC06 { get; set; }
        public Single? ASEF15_PAAC06 { get; set; }
        public Single? ASEF09_PAAC07 { get; set; }
        public Single? ASEF10_PAAC07 { get; set; }
        public Single? ASEF11_PAAC07 { get; set; }
        public Single? ASEF12_PAAC07 { get; set; }
        public Single? ASEF13_PAAC07 { get; set; }
        public Single? ASEF14_PAAC07 { get; set; }
        public Single? ASEF15_PAAC07 { get; set; }
        public Single? ASEF09_PAAC08 { get; set; }
        public Single? ASEF10_PAAC08 { get; set; }
        public Single? ASEF11_PAAC08 { get; set; }
        public Single? ASEF12_PAAC08 { get; set; }
        public Single? ASEF13_PAAC08 { get; set; }
        public Single? ASEF14_PAAC08 { get; set; }
        public Single? ASEF15_PAAC08 { get; set; }
        public Single? ASEF09_PAAC09 { get; set; }
        public Single? ASEF10_PAAC09 { get; set; }
        public Single? ASEF11_PAAC09 { get; set; }
        public Single? ASEF12_PAAC09 { get; set; }
        public Single? ASEF13_PAAC09 { get; set; }
        public Single? ASEF14_PAAC09 { get; set; }
        public Single? ASEF15_PAAC09 { get; set; }
        public Single? ASEF09_PAAC10 { get; set; }
        public Single? ASEF10_PAAC10 { get; set; }
        public Single? ASEF11_PAAC10 { get; set; }
        public Single? ASEF12_PAAC10 { get; set; }
        public Single? ASEF13_PAAC10 { get; set; }
        public Single? ASEF14_PAAC10 { get; set; }
        public Single? ASEF15_PAAC10 { get; set; }
        public Single? ASEF09_PAAC11 { get; set; }
        public Single? ASEF10_PAAC11 { get; set; }
        public Single? ASEF11_PAAC11 { get; set; }
        public Single? ASEF12_PAAC11 { get; set; }
        public Single? ASEF13_PAAC11 { get; set; }
        public Single? ASEF14_PAAC11 { get; set; }
        public Single? ASEF15_PAAC11 { get; set; }
        public Single? ASEF09_PAAC12 { get; set; }
        public Single? ASEF10_PAAC12 { get; set; }
        public Single? ASEF11_PAAC12 { get; set; }
        public Single? ASEF12_PAAC12 { get; set; }
        public Single? ASEF13_PAAC12 { get; set; }
        public Single? ASEF14_PAAC12 { get; set; }
        public Single? ASEF15_PAAC12 { get; set; }
        public Single? ASEF09_PAAC13 { get; set; }
        public Single? ASEF10_PAAC13 { get; set; }
        public Single? ASEF11_PAAC13 { get; set; }
        public Single? ASEF12_PAAC13 { get; set; }
        public Single? ASEF13_PAAC13 { get; set; }
        public Single? ASEF14_PAAC13 { get; set; }
        public Single? ASEF15_PAAC13 { get; set; }
        public Single? ASEF09_PAAC14 { get; set; }
        public Single? ASEF10_PAAC14 { get; set; }
        public Single? ASEF11_PAAC14 { get; set; }
        public Single? ASEF12_PAAC14 { get; set; }
        public Single? ASEF13_PAAC14 { get; set; }
        public Single? ASEF14_PAAC14 { get; set; }
        public Single? ASEF15_PAAC14 { get; set; }
        public Single? ASEF09_PAAC15 { get; set; }
        public Single? ASEF10_PAAC15 { get; set; }
        public Single? ASEF11_PAAC15 { get; set; }
        public Single? ASEF12_PAAC15 { get; set; }
        public Single? ASEF13_PAAC15 { get; set; }
        public Single? ASEF14_PAAC15 { get; set; }
        public Single? ASEF15_PAAC15 { get; set; }
        public Single? ASEF09_PAAC16 { get; set; }
        public Single? ASEF10_PAAC16 { get; set; }
        public Single? ASEF11_PAAC16 { get; set; }
        public Single? ASEF12_PAAC16 { get; set; }
        public Single? ASEF13_PAAC16 { get; set; }
        public Single? ASEF14_PAAC16 { get; set; }
        public Single? ASEF15_PAAC16 { get; set; }
        public Single? ASEF09_PAAC17 { get; set; }
        public Single? ASEF10_PAAC17 { get; set; }
        public Single? ASEF11_PAAC17 { get; set; }
        public Single? ASEF12_PAAC17 { get; set; }
        public Single? ASEF13_PAAC17 { get; set; }
        public Single? ASEF14_PAAC17 { get; set; }
        public Single? ASEF15_PAAC17 { get; set; }
        public Single? ASEF09_PAAC18 { get; set; }
        public Single? ASEF10_PAAC18 { get; set; }
        public Single? ASEF11_PAAC18 { get; set; }
        public Single? ASEF12_PAAC18 { get; set; }
        public Single? ASEF13_PAAC18 { get; set; }
        public Single? ASEF14_PAAC18 { get; set; }
        public Single? ASEF15_PAAC18 { get; set; }
        public Single? ASEF09_PAAC19 { get; set; }
        public Single? ASEF10_PAAC19 { get; set; }
        public Single? ASEF11_PAAC19 { get; set; }
        public Single? ASEF12_PAAC19 { get; set; }
        public Single? ASEF13_PAAC19 { get; set; }
        public Single? ASEF14_PAAC19 { get; set; }
        public Single? ASEF15_PAAC19 { get; set; }
        public Single? ASEF09_PAAC20 { get; set; }
        public Single? ASEF10_PAAC20 { get; set; }
        public Single? ASEF11_PAAC20 { get; set; }
        public Single? ASEF12_PAAC20 { get; set; }
        public Single? ASEF13_PAAC20 { get; set; }
        public Single? ASEF14_PAAC20 { get; set; }
        public Single? ASEF15_PAAC20 { get; set; }
        public Single? ASEF09_PAAC21 { get; set; }
        public Single? ASEF10_PAAC21 { get; set; }
        public Single? ASEF11_PAAC21 { get; set; }
        public Single? ASEF12_PAAC21 { get; set; }
        public Single? ASEF13_PAAC21 { get; set; }
        public Single? ASEF14_PAAC21 { get; set; }
        public Single? ASEF15_PAAC21 { get; set; }
        public Single? ASEF09_PAAC22 { get; set; }
        public Single? ASEF10_PAAC22 { get; set; }
        public Single? ASEF11_PAAC22 { get; set; }
        public Single? ASEF12_PAAC22 { get; set; }
        public Single? ASEF13_PAAC22 { get; set; }
        public Single? ASEF14_PAAC22 { get; set; }
        public Single? ASEF15_PAAC22 { get; set; }
        public Single? ASEF09_PAAC23 { get; set; }
        public Single? ASEF10_PAAC23 { get; set; }
        public Single? ASEF11_PAAC23 { get; set; }
        public Single? ASEF12_PAAC23 { get; set; }
        public Single? ASEF13_PAAC23 { get; set; }
        public Single? ASEF14_PAAC23 { get; set; }
        public Single? ASEF15_PAAC23 { get; set; }
        public Single? ASEF09_PAAC24 { get; set; }
        public Single? ASEF10_PAAC24 { get; set; }
        public Single? ASEF11_PAAC24 { get; set; }
        public Single? ASEF12_PAAC24 { get; set; }
        public Single? ASEF13_PAAC24 { get; set; }
        public Single? ASEF14_PAAC24 { get; set; }
        public Single? ASEF15_PAAC24 { get; set; }
        public Single? ASEF09_PAAC25 { get; set; }
        public Single? ASEF10_PAAC25 { get; set; }
        public Single? ASEF11_PAAC25 { get; set; }
        public Single? ASEF12_PAAC25 { get; set; }
        public Single? ASEF13_PAAC25 { get; set; }
        public Single? ASEF14_PAAC25 { get; set; }
        public Single? ASEF15_PAAC25 { get; set; }
        public Single? ASEF09_PAAC26 { get; set; }
        public Single? ASEF10_PAAC26 { get; set; }
        public Single? ASEF11_PAAC26 { get; set; }
        public Single? ASEF12_PAAC26 { get; set; }
        public Single? ASEF13_PAAC26 { get; set; }
        public Single? ASEF14_PAAC26 { get; set; }
        public Single? ASEF15_PAAC26 { get; set; }
        public Single? ASEF09_PAAC27 { get; set; }
        public Single? ASEF10_PAAC27 { get; set; }
        public Single? ASEF11_PAAC27 { get; set; }
        public Single? ASEF12_PAAC27 { get; set; }
        public Single? ASEF13_PAAC27 { get; set; }
        public Single? ASEF14_PAAC27 { get; set; }
        public Single? ASEF15_PAAC27 { get; set; }
        public Single? ASEF09_PAAC29 { get; set; }
        public Single? ASEF10_PAAC29 { get; set; }
        public Single? ASEF11_PAAC29 { get; set; }
        public Single? ASEF12_PAAC29 { get; set; }
        public Single? ASEF13_PAAC29 { get; set; }
        public Single? ASEF14_PAAC29 { get; set; }
        public Single? ASEF15_PAAC29 { get; set; }
        public Single? ASEF09_PAAC30 { get; set; }
        public Single? ASEF10_PAAC30 { get; set; }
        public Single? ASEF11_PAAC30 { get; set; }
        public Single? ASEF12_PAAC30 { get; set; }
        public Single? ASEF13_PAAC30 { get; set; }
        public Single? ASEF14_PAAC30 { get; set; }
        public Single? ASEF15_PAAC30 { get; set; }
        public Single? ASEF09_PAAC31 { get; set; }
        public Single? ASEF10_PAAC31 { get; set; }
        public Single? ASEF11_PAAC31 { get; set; }
        public Single? ASEF12_PAAC31 { get; set; }
        public Single? ASEF13_PAAC31 { get; set; }
        public Single? ASEF14_PAAC31 { get; set; }
        public Single? ASEF15_PAAC31 { get; set; }
        public Single? ASEF09_PAAC32 { get; set; }
        public Single? ASEF10_PAAC32 { get; set; }
        public Single? ASEF11_PAAC32 { get; set; }
        public Single? ASEF12_PAAC32 { get; set; }
        public Single? ASEF13_PAAC32 { get; set; }
        public Single? ASEF14_PAAC32 { get; set; }
        public Single? ASEF15_PAAC32 { get; set; }
        public Single? ASEF09_PAAC33 { get; set; }
        public Single? ASEF10_PAAC33 { get; set; }
        public Single? ASEF11_PAAC33 { get; set; }
        public Single? ASEF12_PAAC33 { get; set; }
        public Single? ASEF13_PAAC33 { get; set; }
        public Single? ASEF14_PAAC33 { get; set; }
        public Single? ASEF15_PAAC33 { get; set; }
        public Single? ASEF09_PAAC34 { get; set; }
        public Single? ASEF10_PAAC34 { get; set; }
        public Single? ASEF11_PAAC34 { get; set; }
        public Single? ASEF12_PAAC34 { get; set; }
        public Single? ASEF13_PAAC34 { get; set; }
        public Single? ASEF14_PAAC34 { get; set; }
        public Single? ASEF15_PAAC34 { get; set; }
        public Single? ASEF09_PAAC35 { get; set; }
        public Single? ASEF10_PAAC35 { get; set; }
        public Single? ASEF11_PAAC35 { get; set; }
        public Single? ASEF12_PAAC35 { get; set; }
        public Single? ASEF13_PAAC35 { get; set; }
        public Single? ASEF14_PAAC35 { get; set; }
        public Single? ASEF15_PAAC35 { get; set; }
        public Single? ASEF09_PAAC36 { get; set; }
        public Single? ASEF10_PAAC36 { get; set; }
        public Single? ASEF11_PAAC36 { get; set; }
        public Single? ASEF12_PAAC36 { get; set; }
        public Single? ASEF13_PAAC36 { get; set; }
        public Single? ASEF14_PAAC36 { get; set; }
        public Single? ASEF15_PAAC36 { get; set; }
        public Single? ASEF09_PAAC37 { get; set; }
        public Single? ASEF10_PAAC37 { get; set; }
        public Single? ASEF11_PAAC37 { get; set; }
        public Single? ASEF12_PAAC37 { get; set; }
        public Single? ASEF13_PAAC37 { get; set; }
        public Single? ASEF14_PAAC37 { get; set; }
        public Single? ASEF15_PAAC37 { get; set; }
        public Single? ASEF09_PAAC38 { get; set; }
        public Single? ASEF10_PAAC38 { get; set; }
        public Single? ASEF11_PAAC38 { get; set; }
        public Single? ASEF12_PAAC38 { get; set; }
        public Single? ASEF13_PAAC38 { get; set; }
        public Single? ASEF14_PAAC38 { get; set; }
        public Single? ASEF15_PAAC38 { get; set; }
        public Single? ASEF09_PAAC39 { get; set; }
        public Single? ASEF10_PAAC39 { get; set; }
        public Single? ASEF11_PAAC39 { get; set; }
        public Single? ASEF12_PAAC39 { get; set; }
        public Single? ASEF13_PAAC39 { get; set; }
        public Single? ASEF14_PAAC39 { get; set; }
        public Single? ASEF15_PAAC39 { get; set; }
        public Single? ASEF09_PAAC40 { get; set; }
        public Single? ASEF10_PAAC40 { get; set; }
        public Single? ASEF11_PAAC40 { get; set; }
        public Single? ASEF12_PAAC40 { get; set; }
        public Single? ASEF13_PAAC40 { get; set; }
        public Single? ASEF14_PAAC40 { get; set; }
        public Single? ASEF15_PAAC40 { get; set; }
        public Single? ASEF09_PAAC41 { get; set; }
        public Single? ASEF10_PAAC41 { get; set; }
        public Single? ASEF11_PAAC41 { get; set; }
        public Single? ASEF12_PAAC41 { get; set; }
        public Single? ASEF13_PAAC41 { get; set; }
        public Single? ASEF14_PAAC41 { get; set; }
        public Single? ASEF15_PAAC41 { get; set; }
        public Single? ASEF09_PAAC42 { get; set; }
        public Single? ASEF10_PAAC42 { get; set; }
        public Single? ASEF11_PAAC42 { get; set; }
        public Single? ASEF12_PAAC42 { get; set; }
        public Single? ASEF13_PAAC42 { get; set; }
        public Single? ASEF14_PAAC42 { get; set; }
        public Single? ASEF15_PAAC42 { get; set; }
        public Single? ASEF09_PAAC43 { get; set; }
        public Single? ASEF10_PAAC43 { get; set; }
        public Single? ASEF11_PAAC43 { get; set; }
        public Single? ASEF12_PAAC43 { get; set; }
        public Single? ASEF13_PAAC43 { get; set; }
        public Single? ASEF14_PAAC43 { get; set; }
        public Single? ASEF15_PAAC43 { get; set; }
        public Single? ASEF09_PAAC44 { get; set; }
        public Single? ASEF10_PAAC44 { get; set; }
        public Single? ASEF11_PAAC44 { get; set; }
        public Single? ASEF12_PAAC44 { get; set; }
        public Single? ASEF13_PAAC44 { get; set; }
        public Single? ASEF14_PAAC44 { get; set; }
        public Single? ASEF15_PAAC44 { get; set; }
        public Single? ASEF09_PAAC45 { get; set; }
        public Single? ASEF10_PAAC45 { get; set; }
        public Single? ASEF11_PAAC45 { get; set; }
        public Single? ASEF12_PAAC45 { get; set; }
        public Single? ASEF13_PAAC45 { get; set; }
        public Single? ASEF14_PAAC45 { get; set; }
        public Single? ASEF15_PAAC45 { get; set; }
        public Single? ASEF09_PAAC46 { get; set; }
        public Single? ASEF10_PAAC46 { get; set; }
        public Single? ASEF11_PAAC46 { get; set; }
        public Single? ASEF12_PAAC46 { get; set; }
        public Single? ASEF13_PAAC46 { get; set; }
        public Single? ASEF14_PAAC46 { get; set; }
        public Single? ASEF15_PAAC46 { get; set; }
        public Single? ASEF09_PAAC47 { get; set; }
        public Single? ASEF10_PAAC47 { get; set; }
        public Single? ASEF11_PAAC47 { get; set; }
        public Single? ASEF12_PAAC47 { get; set; }
        public Single? ASEF13_PAAC47 { get; set; }
        public Single? ASEF14_PAAC47 { get; set; }
        public Single? ASEF15_PAAC47 { get; set; }
        public Single? ASEF09_PAAC48 { get; set; }
        public Single? ASEF10_PAAC48 { get; set; }
        public Single? ASEF11_PAAC48 { get; set; }
        public Single? ASEF12_PAAC48 { get; set; }
        public Single? ASEF13_PAAC48 { get; set; }
        public Single? ASEF14_PAAC48 { get; set; }
        public Single? ASEF15_PAAC48 { get; set; }
        public Single? ASEF09_PAAC49 { get; set; }
        public Single? ASEF10_PAAC49 { get; set; }
        public Single? ASEF11_PAAC49 { get; set; }
        public Single? ASEF12_PAAC49 { get; set; }
        public Single? ASEF13_PAAC49 { get; set; }
        public Single? ASEF14_PAAC49 { get; set; }
        public Single? ASEF15_PAAC49 { get; set; }
        public Single? ASEF09_PAAC50 { get; set; }
        public Single? ASEF10_PAAC50 { get; set; }
        public Single? ASEF11_PAAC50 { get; set; }
        public Single? ASEF12_PAAC50 { get; set; }
        public Single? ASEF13_PAAC50 { get; set; }
        public Single? ASEF14_PAAC50 { get; set; }
        public Single? ASEF15_PAAC50 { get; set; }
        public Single? BSEF09_PBAC01 { get; set; }
        public Single? BSEF10_PBAC01 { get; set; }
        public Single? BSEF11_PBAC01 { get; set; }
        public Single? BSEF12_PBAC01 { get; set; }
        public Single? BSEF13_PBAC01 { get; set; }
        public Single? BSEF14_PBAC01 { get; set; }
        public Single? BSEF15_PBAC01 { get; set; }
        public Single? BSEF09_PBAC02 { get; set; }
        public Single? BSEF10_PBAC02 { get; set; }
        public Single? BSEF11_PBAC02 { get; set; }
        public Single? BSEF12_PBAC02 { get; set; }
        public Single? BSEF13_PBAC02 { get; set; }
        public Single? BSEF14_PBAC02 { get; set; }
        public Single? BSEF15_PBAC02 { get; set; }
        public Single? BSEF09_PBAC03 { get; set; }
        public Single? BSEF10_PBAC03 { get; set; }
        public Single? BSEF11_PBAC03 { get; set; }
        public Single? BSEF12_PBAC03 { get; set; }
        public Single? BSEF13_PBAC03 { get; set; }
        public Single? BSEF14_PBAC03 { get; set; }
        public Single? BSEF15_PBAC03 { get; set; }
        public Single? BSEF09_PBAC04 { get; set; }
        public Single? BSEF10_PBAC04 { get; set; }
        public Single? BSEF11_PBAC04 { get; set; }
        public Single? BSEF12_PBAC04 { get; set; }
        public Single? BSEF13_PBAC04 { get; set; }
        public Single? BSEF14_PBAC04 { get; set; }
        public Single? BSEF15_PBAC04 { get; set; }
        public Single? BSEF09_PBAC05 { get; set; }
        public Single? BSEF10_PBAC05 { get; set; }
        public Single? BSEF11_PBAC05 { get; set; }
        public Single? BSEF12_PBAC05 { get; set; }
        public Single? BSEF13_PBAC05 { get; set; }
        public Single? BSEF14_PBAC05 { get; set; }
        public Single? BSEF15_PBAC05 { get; set; }
        public Single? BSEF09_PBAC06 { get; set; }
        public Single? BSEF10_PBAC06 { get; set; }
        public Single? BSEF11_PBAC06 { get; set; }
        public Single? BSEF12_PBAC06 { get; set; }
        public Single? BSEF13_PBAC06 { get; set; }
        public Single? BSEF14_PBAC06 { get; set; }
        public Single? BSEF15_PBAC06 { get; set; }
        public Single? BSEF09_PBAC07 { get; set; }
        public Single? BSEF10_PBAC07 { get; set; }
        public Single? BSEF11_PBAC07 { get; set; }
        public Single? BSEF12_PBAC07 { get; set; }
        public Single? BSEF13_PBAC07 { get; set; }
        public Single? BSEF14_PBAC07 { get; set; }
        public Single? BSEF15_PBAC07 { get; set; }
        public Single? BSEF09_PBAC08 { get; set; }
        public Single? BSEF10_PBAC08 { get; set; }
        public Single? BSEF11_PBAC08 { get; set; }
        public Single? BSEF12_PBAC08 { get; set; }
        public Single? BSEF13_PBAC08 { get; set; }
        public Single? BSEF14_PBAC08 { get; set; }
        public Single? BSEF15_PBAC08 { get; set; }
        public Single? BSEF09_PBAC09 { get; set; }
        public Single? BSEF10_PBAC09 { get; set; }
        public Single? BSEF11_PBAC09 { get; set; }
        public Single? BSEF12_PBAC09 { get; set; }
        public Single? BSEF13_PBAC09 { get; set; }
        public Single? BSEF14_PBAC09 { get; set; }
        public Single? BSEF15_PBAC09 { get; set; }
        public Single? BSEF09_PBAC10 { get; set; }
        public Single? BSEF10_PBAC10 { get; set; }
        public Single? BSEF11_PBAC10 { get; set; }
        public Single? BSEF12_PBAC10 { get; set; }
        public Single? BSEF13_PBAC10 { get; set; }
        public Single? BSEF14_PBAC10 { get; set; }
        public Single? BSEF15_PBAC10 { get; set; }
        public Single? BSEF09_PBAC11 { get; set; }
        public Single? BSEF10_PBAC11 { get; set; }
        public Single? BSEF11_PBAC11 { get; set; }
        public Single? BSEF12_PBAC11 { get; set; }
        public Single? BSEF13_PBAC11 { get; set; }
        public Single? BSEF14_PBAC11 { get; set; }
        public Single? BSEF15_PBAC11 { get; set; }
        public Single? BSEF09_PBAC12 { get; set; }
        public Single? BSEF10_PBAC12 { get; set; }
        public Single? BSEF11_PBAC12 { get; set; }
        public Single? BSEF12_PBAC12 { get; set; }
        public Single? BSEF13_PBAC12 { get; set; }
        public Single? BSEF14_PBAC12 { get; set; }
        public Single? BSEF15_PBAC12 { get; set; }
        public Single? BSEF09_PBAC14 { get; set; }
        public Single? BSEF10_PBAC14 { get; set; }
        public Single? BSEF11_PBAC14 { get; set; }
        public Single? BSEF12_PBAC14 { get; set; }
        public Single? BSEF13_PBAC14 { get; set; }
        public Single? BSEF14_PBAC14 { get; set; }
        public Single? BSEF15_PBAC14 { get; set; }
        public Single? BSEF09_PBAC15 { get; set; }
        public Single? BSEF10_PBAC15 { get; set; }
        public Single? BSEF11_PBAC15 { get; set; }
        public Single? BSEF12_PBAC15 { get; set; }
        public Single? BSEF13_PBAC15 { get; set; }
        public Single? BSEF14_PBAC15 { get; set; }
        public Single? BSEF15_PBAC15 { get; set; }
        public Single? BSEF09_PBAC16 { get; set; }
        public Single? BSEF10_PBAC16 { get; set; }
        public Single? BSEF11_PBAC16 { get; set; }
        public Single? BSEF12_PBAC16 { get; set; }
        public Single? BSEF13_PBAC16 { get; set; }
        public Single? BSEF14_PBAC16 { get; set; }
        public Single? BSEF15_PBAC16 { get; set; }
        public Single? BSEF09_PBAC17 { get; set; }
        public Single? BSEF10_PBAC17 { get; set; }
        public Single? BSEF11_PBAC17 { get; set; }
        public Single? BSEF12_PBAC17 { get; set; }
        public Single? BSEF13_PBAC17 { get; set; }
        public Single? BSEF14_PBAC17 { get; set; }
        public Single? BSEF15_PBAC17 { get; set; }
        public Single? BSEF09_PBAC18 { get; set; }
        public Single? BSEF10_PBAC18 { get; set; }
        public Single? BSEF11_PBAC18 { get; set; }
        public Single? BSEF12_PBAC18 { get; set; }
        public Single? BSEF13_PBAC18 { get; set; }
        public Single? BSEF14_PBAC18 { get; set; }
        public Single? BSEF15_PBAC18 { get; set; }
        public Single? BSEF09_PBAC19 { get; set; }
        public Single? BSEF10_PBAC19 { get; set; }
        public Single? BSEF11_PBAC19 { get; set; }
        public Single? BSEF12_PBAC19 { get; set; }
        public Single? BSEF13_PBAC19 { get; set; }
        public Single? BSEF14_PBAC19 { get; set; }
        public Single? BSEF15_PBAC19 { get; set; }

    }
}
