using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TP_DSYNC.Models.DataDefine.B3
{
    public class MSPCSTATS
    {
        public int AUTOID { get; set; }
        public DateTime? DATETIME { get; set; }
        public Single? ASEF01_PAAC04 { get; set; }
        public Single? ASEF02_PAAC04 { get; set; }
        public Single? ASEF03_PAAC04 { get; set; }
        public Single? ASEF04_PAAC04 { get; set; }
        public Single? ASEF05_PAAC04 { get; set; }
        public Single? ASEF06_PAAC04 { get; set; }
        public Single? ASEF07_PAAC04 { get; set; }
        public Single? ASEF08_PAAC04 { get; set; }
        public Single? ASEF01_PAAC05 { get; set; }
        public Single? ASEF02_PAAC05 { get; set; }
        public Single? ASEF03_PAAC05 { get; set; }
        public Single? ASEF04_PAAC05 { get; set; }
        public Single? ASEF05_PAAC05 { get; set; }
        public Single? ASEF06_PAAC05 { get; set; }
        public Single? ASEF07_PAAC05 { get; set; }
        public Single? ASEF08_PAAC05 { get; set; }
        public Single? ASEF01_PAAC06 { get; set; }
        public Single? ASEF02_PAAC06 { get; set; }
        public Single? ASEF03_PAAC06 { get; set; }
        public Single? ASEF04_PAAC06 { get; set; }
        public Single? ASEF05_PAAC06 { get; set; }
        public Single? ASEF06_PAAC06 { get; set; }
        public Single? ASEF07_PAAC06 { get; set; }
        public Single? ASEF08_PAAC06 { get; set; }
        public Single? ASEF01_PAAC07 { get; set; }
        public Single? ASEF02_PAAC07 { get; set; }
        public Single? ASEF03_PAAC07 { get; set; }
        public Single? ASEF04_PAAC07 { get; set; }
        public Single? ASEF05_PAAC07 { get; set; }
        public Single? ASEF06_PAAC07 { get; set; }
        public Single? ASEF07_PAAC07 { get; set; }
        public Single? ASEF08_PAAC07 { get; set; }
        public Single? ASEF01_PAAC09 { get; set; }
        public Single? ASEF02_PAAC09 { get; set; }
        public Single? ASEF03_PAAC09 { get; set; }
        public Single? ASEF04_PAAC09 { get; set; }
        public Single? ASEF05_PAAC09 { get; set; }
        public Single? ASEF06_PAAC09 { get; set; }
        public Single? ASEF07_PAAC09 { get; set; }
        public Single? ASEF08_PAAC09 { get; set; }
        public Single? ASEF01_PAAC10 { get; set; }
        public Single? ASEF02_PAAC10 { get; set; }
        public Single? ASEF03_PAAC10 { get; set; }
        public Single? ASEF04_PAAC10 { get; set; }
        public Single? ASEF05_PAAC10 { get; set; }
        public Single? ASEF06_PAAC10 { get; set; }
        public Single? ASEF07_PAAC10 { get; set; }
        public Single? ASEF08_PAAC10 { get; set; }
        public Single? ASEF01_PAAC11 { get; set; }
        public Single? ASEF02_PAAC11 { get; set; }
        public Single? ASEF03_PAAC11 { get; set; }
        public Single? ASEF04_PAAC11 { get; set; }
        public Single? ASEF05_PAAC11 { get; set; }
        public Single? ASEF06_PAAC11 { get; set; }
        public Single? ASEF07_PAAC11 { get; set; }
        public Single? ASEF08_PAAC11 { get; set; }
        public Single? ASEF01_PAAC12 { get; set; }
        public Single? ASEF02_PAAC12 { get; set; }
        public Single? ASEF03_PAAC12 { get; set; }
        public Single? ASEF04_PAAC12 { get; set; }
        public Single? ASEF05_PAAC12 { get; set; }
        public Single? ASEF06_PAAC12 { get; set; }
        public Single? ASEF07_PAAC12 { get; set; }
        public Single? ASEF08_PAAC12 { get; set; }
        public Single? ASEF01_PAAC13 { get; set; }
        public Single? ASEF02_PAAC13 { get; set; }
        public Single? ASEF03_PAAC13 { get; set; }
        public Single? ASEF04_PAAC13 { get; set; }
        public Single? ASEF05_PAAC13 { get; set; }
        public Single? ASEF06_PAAC13 { get; set; }
        public Single? ASEF07_PAAC13 { get; set; }
        public Single? ASEF08_PAAC13 { get; set; }
        public Single? ASEF01_PAAC18 { get; set; }
        public Single? ASEF02_PAAC18 { get; set; }
        public Single? ASEF03_PAAC18 { get; set; }
        public Single? ASEF04_PAAC18 { get; set; }
        public Single? ASEF05_PAAC18 { get; set; }
        public Single? ASEF06_PAAC18 { get; set; }
        public Single? ASEF07_PAAC18 { get; set; }
        public Single? ASEF08_PAAC18 { get; set; }
        public Single? ASEF01_PAAC19 { get; set; }
        public Single? ASEF02_PAAC19 { get; set; }
        public Single? ASEF03_PAAC19 { get; set; }
        public Single? ASEF04_PAAC19 { get; set; }
        public Single? ASEF05_PAAC19 { get; set; }
        public Single? ASEF06_PAAC19 { get; set; }
        public Single? ASEF07_PAAC19 { get; set; }
        public Single? ASEF08_PAAC19 { get; set; }
        public Single? ASEF01_PAAC20 { get; set; }
        public Single? ASEF02_PAAC20 { get; set; }
        public Single? ASEF03_PAAC20 { get; set; }
        public Single? ASEF04_PAAC20 { get; set; }
        public Single? ASEF05_PAAC20 { get; set; }
        public Single? ASEF06_PAAC20 { get; set; }
        public Single? ASEF07_PAAC20 { get; set; }
        public Single? ASEF08_PAAC20 { get; set; }
        public Single? ASEF01_PAAC23 { get; set; }
        public Single? ASEF02_PAAC23 { get; set; }
        public Single? ASEF03_PAAC23 { get; set; }
        public Single? ASEF04_PAAC23 { get; set; }
        public Single? ASEF05_PAAC23 { get; set; }
        public Single? ASEF06_PAAC23 { get; set; }
        public Single? ASEF07_PAAC23 { get; set; }
        public Single? ASEF08_PAAC23 { get; set; }
        public Single? ASEF01_PAAC24 { get; set; }
        public Single? ASEF02_PAAC24 { get; set; }
        public Single? ASEF03_PAAC24 { get; set; }
        public Single? ASEF04_PAAC24 { get; set; }
        public Single? ASEF05_PAAC24 { get; set; }
        public Single? ASEF06_PAAC24 { get; set; }
        public Single? ASEF07_PAAC24 { get; set; }
        public Single? ASEF08_PAAC24 { get; set; }
        public Single? ASEF01_PAAC28 { get; set; }
        public Single? ASEF02_PAAC28 { get; set; }
        public Single? ASEF03_PAAC28 { get; set; }
        public Single? ASEF04_PAAC28 { get; set; }
        public Single? ASEF05_PAAC28 { get; set; }
        public Single? ASEF06_PAAC28 { get; set; }
        public Single? ASEF07_PAAC28 { get; set; }
        public Single? ASEF08_PAAC28 { get; set; }
        public Single? ASEF01_PAAC33 { get; set; }
        public Single? ASEF02_PAAC33 { get; set; }
        public Single? ASEF03_PAAC33 { get; set; }
        public Single? ASEF04_PAAC33 { get; set; }
        public Single? ASEF05_PAAC33 { get; set; }
        public Single? ASEF06_PAAC33 { get; set; }
        public Single? ASEF07_PAAC33 { get; set; }
        public Single? ASEF08_PAAC33 { get; set; }
        public Single? ASEF01_PAAC34 { get; set; }
        public Single? ASEF02_PAAC34 { get; set; }
        public Single? ASEF03_PAAC34 { get; set; }
        public Single? ASEF04_PAAC34 { get; set; }
        public Single? ASEF05_PAAC34 { get; set; }
        public Single? ASEF06_PAAC34 { get; set; }
        public Single? ASEF07_PAAC34 { get; set; }
        public Single? ASEF08_PAAC34 { get; set; }
        public Single? ASEF01_PAAC35 { get; set; }
        public Single? ASEF02_PAAC35 { get; set; }
        public Single? ASEF03_PAAC35 { get; set; }
        public Single? ASEF04_PAAC35 { get; set; }
        public Single? ASEF05_PAAC35 { get; set; }
        public Single? ASEF06_PAAC35 { get; set; }
        public Single? ASEF07_PAAC35 { get; set; }
        public Single? ASEF08_PAAC35 { get; set; }
        public Single? ASEF01_PAAC36 { get; set; }
        public Single? ASEF02_PAAC36 { get; set; }
        public Single? ASEF03_PAAC36 { get; set; }
        public Single? ASEF04_PAAC36 { get; set; }
        public Single? ASEF05_PAAC36 { get; set; }
        public Single? ASEF06_PAAC36 { get; set; }
        public Single? ASEF07_PAAC36 { get; set; }
        public Single? ASEF08_PAAC36 { get; set; }
        public Single? ASEF01_PAAC37 { get; set; }
        public Single? ASEF02_PAAC37 { get; set; }
        public Single? ASEF03_PAAC37 { get; set; }
        public Single? ASEF04_PAAC37 { get; set; }
        public Single? ASEF05_PAAC37 { get; set; }
        public Single? ASEF06_PAAC37 { get; set; }
        public Single? ASEF07_PAAC37 { get; set; }
        public Single? ASEF08_PAAC37 { get; set; }
        public Single? ASEF01_PAAC38 { get; set; }
        public Single? ASEF02_PAAC38 { get; set; }
        public Single? ASEF03_PAAC38 { get; set; }
        public Single? ASEF04_PAAC38 { get; set; }
        public Single? ASEF05_PAAC38 { get; set; }
        public Single? ASEF06_PAAC38 { get; set; }
        public Single? ASEF07_PAAC38 { get; set; }
        public Single? ASEF08_PAAC38 { get; set; }
        public Single? ASEF01_PAAC39 { get; set; }
        public Single? ASEF02_PAAC39 { get; set; }
        public Single? ASEF03_PAAC39 { get; set; }
        public Single? ASEF04_PAAC39 { get; set; }
        public Single? ASEF05_PAAC39 { get; set; }
        public Single? ASEF06_PAAC39 { get; set; }
        public Single? ASEF07_PAAC39 { get; set; }
        public Single? ASEF08_PAAC39 { get; set; }
        public Single? ASEF01_PAAC40 { get; set; }
        public Single? ASEF02_PAAC40 { get; set; }
        public Single? ASEF03_PAAC40 { get; set; }
        public Single? ASEF04_PAAC40 { get; set; }
        public Single? ASEF05_PAAC40 { get; set; }
        public Single? ASEF06_PAAC40 { get; set; }
        public Single? ASEF07_PAAC40 { get; set; }
        public Single? ASEF08_PAAC40 { get; set; }
        public Single? ASEF01_PAAC41 { get; set; }
        public Single? ASEF02_PAAC41 { get; set; }
        public Single? ASEF03_PAAC41 { get; set; }
        public Single? ASEF04_PAAC41 { get; set; }
        public Single? ASEF05_PAAC41 { get; set; }
        public Single? ASEF06_PAAC41 { get; set; }
        public Single? ASEF07_PAAC41 { get; set; }
        public Single? ASEF08_PAAC41 { get; set; }
        public Single? ASEF01_PAAC42 { get; set; }
        public Single? ASEF02_PAAC42 { get; set; }
        public Single? ASEF03_PAAC42 { get; set; }
        public Single? ASEF04_PAAC42 { get; set; }
        public Single? ASEF05_PAAC42 { get; set; }
        public Single? ASEF06_PAAC42 { get; set; }
        public Single? ASEF07_PAAC42 { get; set; }
        public Single? ASEF08_PAAC42 { get; set; }
        public Single? ASEF01_PAAC43 { get; set; }
        public Single? ASEF02_PAAC43 { get; set; }
        public Single? ASEF03_PAAC43 { get; set; }
        public Single? ASEF04_PAAC43 { get; set; }
        public Single? ASEF05_PAAC43 { get; set; }
        public Single? ASEF06_PAAC43 { get; set; }
        public Single? ASEF07_PAAC43 { get; set; }
        public Single? ASEF08_PAAC43 { get; set; }
        public Single? ASEF01_PAAC45 { get; set; }
        public Single? ASEF02_PAAC45 { get; set; }
        public Single? ASEF03_PAAC45 { get; set; }
        public Single? ASEF04_PAAC45 { get; set; }
        public Single? ASEF05_PAAC45 { get; set; }
        public Single? ASEF06_PAAC45 { get; set; }
        public Single? ASEF07_PAAC45 { get; set; }
        public Single? ASEF08_PAAC45 { get; set; }
        public Single? ASEF01_PAAC46 { get; set; }
        public Single? ASEF02_PAAC46 { get; set; }
        public Single? ASEF03_PAAC46 { get; set; }
        public Single? ASEF04_PAAC46 { get; set; }
        public Single? ASEF05_PAAC46 { get; set; }
        public Single? ASEF06_PAAC46 { get; set; }
        public Single? ASEF07_PAAC46 { get; set; }
        public Single? ASEF08_PAAC46 { get; set; }
        public Single? BSEF01_PBAC01 { get; set; }
        public Single? BSEF02_PBAC01 { get; set; }
        public Single? BSEF03_PBAC01 { get; set; }
        public Single? BSEF04_PBAC01 { get; set; }
        public Single? BSEF05_PBAC01 { get; set; }
        public Single? BSEF06_PBAC01 { get; set; }
        public Single? BSEF07_PBAC01 { get; set; }
        public Single? BSEF08_PBAC01 { get; set; }
        public Single? BSEF01_PBAC02 { get; set; }
        public Single? BSEF02_PBAC02 { get; set; }
        public Single? BSEF03_PBAC02 { get; set; }
        public Single? BSEF04_PBAC02 { get; set; }
        public Single? BSEF05_PBAC02 { get; set; }
        public Single? BSEF06_PBAC02 { get; set; }
        public Single? BSEF07_PBAC02 { get; set; }
        public Single? BSEF08_PBAC02 { get; set; }
        public Single? BSEF01_PBAC03 { get; set; }
        public Single? BSEF02_PBAC03 { get; set; }
        public Single? BSEF03_PBAC03 { get; set; }
        public Single? BSEF04_PBAC03 { get; set; }
        public Single? BSEF05_PBAC03 { get; set; }
        public Single? BSEF06_PBAC03 { get; set; }
        public Single? BSEF07_PBAC03 { get; set; }
        public Single? BSEF08_PBAC03 { get; set; }
        public Single? BSEF01_PBAC04 { get; set; }
        public Single? BSEF02_PBAC04 { get; set; }
        public Single? BSEF03_PBAC04 { get; set; }
        public Single? BSEF04_PBAC04 { get; set; }
        public Single? BSEF05_PBAC04 { get; set; }
        public Single? BSEF06_PBAC04 { get; set; }
        public Single? BSEF07_PBAC04 { get; set; }
        public Single? BSEF08_PBAC04 { get; set; }
        public Single? BSEF01_PBAC05 { get; set; }
        public Single? BSEF02_PBAC05 { get; set; }
        public Single? BSEF03_PBAC05 { get; set; }
        public Single? BSEF04_PBAC05 { get; set; }
        public Single? BSEF05_PBAC05 { get; set; }
        public Single? BSEF06_PBAC05 { get; set; }
        public Single? BSEF07_PBAC05 { get; set; }
        public Single? BSEF08_PBAC05 { get; set; }
        public Single? BSEF01_PBAC06 { get; set; }
        public Single? BSEF02_PBAC06 { get; set; }
        public Single? BSEF03_PBAC06 { get; set; }
        public Single? BSEF04_PBAC06 { get; set; }
        public Single? BSEF05_PBAC06 { get; set; }
        public Single? BSEF06_PBAC06 { get; set; }
        public Single? BSEF07_PBAC06 { get; set; }
        public Single? BSEF08_PBAC06 { get; set; }
        public Single? BSEF01_PBAC07 { get; set; }
        public Single? BSEF02_PBAC07 { get; set; }
        public Single? BSEF03_PBAC07 { get; set; }
        public Single? BSEF04_PBAC07 { get; set; }
        public Single? BSEF05_PBAC07 { get; set; }
        public Single? BSEF06_PBAC07 { get; set; }
        public Single? BSEF07_PBAC07 { get; set; }
        public Single? BSEF08_PBAC07 { get; set; }
        public Single? BSEF01_PBAC08 { get; set; }
        public Single? BSEF02_PBAC08 { get; set; }
        public Single? BSEF03_PBAC08 { get; set; }
        public Single? BSEF04_PBAC08 { get; set; }
        public Single? BSEF05_PBAC08 { get; set; }
        public Single? BSEF06_PBAC08 { get; set; }
        public Single? BSEF07_PBAC08 { get; set; }
        public Single? BSEF08_PBAC08 { get; set; }
        public Single? BSEF01_PBAC09 { get; set; }
        public Single? BSEF02_PBAC09 { get; set; }
        public Single? BSEF03_PBAC09 { get; set; }
        public Single? BSEF04_PBAC09 { get; set; }
        public Single? BSEF05_PBAC09 { get; set; }
        public Single? BSEF06_PBAC09 { get; set; }
        public Single? BSEF07_PBAC09 { get; set; }
        public Single? BSEF08_PBAC09 { get; set; }
        public Single? BSEF01_PBAC10 { get; set; }
        public Single? BSEF02_PBAC10 { get; set; }
        public Single? BSEF03_PBAC10 { get; set; }
        public Single? BSEF04_PBAC10 { get; set; }
        public Single? BSEF05_PBAC10 { get; set; }
        public Single? BSEF06_PBAC10 { get; set; }
        public Single? BSEF07_PBAC10 { get; set; }
        public Single? BSEF08_PBAC10 { get; set; }
        public Single? BSEF01_PBAC11 { get; set; }
        public Single? BSEF02_PBAC11 { get; set; }
        public Single? BSEF03_PBAC11 { get; set; }
        public Single? BSEF04_PBAC11 { get; set; }
        public Single? BSEF05_PBAC11 { get; set; }
        public Single? BSEF06_PBAC11 { get; set; }
        public Single? BSEF07_PBAC11 { get; set; }
        public Single? BSEF08_PBAC11 { get; set; }
        public Single? BSEF01_PBAC12 { get; set; }
        public Single? BSEF02_PBAC12 { get; set; }
        public Single? BSEF03_PBAC12 { get; set; }
        public Single? BSEF04_PBAC12 { get; set; }
        public Single? BSEF05_PBAC12 { get; set; }
        public Single? BSEF06_PBAC12 { get; set; }
        public Single? BSEF07_PBAC12 { get; set; }
        public Single? BSEF08_PBAC12 { get; set; }
        public Single? BSEF01_PBAC14 { get; set; }
        public Single? BSEF02_PBAC14 { get; set; }
        public Single? BSEF03_PBAC14 { get; set; }
        public Single? BSEF04_PBAC14 { get; set; }
        public Single? BSEF05_PBAC14 { get; set; }
        public Single? BSEF06_PBAC14 { get; set; }
        public Single? BSEF07_PBAC14 { get; set; }
        public Single? BSEF08_PBAC14 { get; set; }
        public Single? BSEF01_PBAC15 { get; set; }
        public Single? BSEF02_PBAC15 { get; set; }
        public Single? BSEF03_PBAC15 { get; set; }
        public Single? BSEF04_PBAC15 { get; set; }
        public Single? BSEF05_PBAC15 { get; set; }
        public Single? BSEF06_PBAC15 { get; set; }
        public Single? BSEF07_PBAC15 { get; set; }
        public Single? BSEF08_PBAC15 { get; set; }
        public Single? BSEF01_PBAC19 { get; set; }
        public Single? BSEF02_PBAC19 { get; set; }
        public Single? BSEF03_PBAC19 { get; set; }
        public Single? BSEF04_PBAC19 { get; set; }
        public Single? BSEF05_PBAC19 { get; set; }
        public Single? BSEF06_PBAC19 { get; set; }
        public Single? BSEF07_PBAC19 { get; set; }
        public Single? BSEF08_PBAC19 { get; set; }
    }
}
