USE [master]
GO
/****** Object:  Database [TP_ALERT]    Script Date: 2020/11/8 下午 04:01:07 ******/
CREATE DATABASE [TP_ALERT]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TP_ALERT', FILENAME = N'D:\DATA\TP_ALERT.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TP_ALERT_log', FILENAME = N'D:\DATA\TP_ALERT_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [TP_ALERT] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TP_ALERT].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TP_ALERT] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TP_ALERT] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TP_ALERT] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TP_ALERT] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TP_ALERT] SET ARITHABORT OFF 
GO
ALTER DATABASE [TP_ALERT] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TP_ALERT] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TP_ALERT] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TP_ALERT] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TP_ALERT] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TP_ALERT] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TP_ALERT] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TP_ALERT] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TP_ALERT] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TP_ALERT] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TP_ALERT] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TP_ALERT] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TP_ALERT] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TP_ALERT] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TP_ALERT] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TP_ALERT] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TP_ALERT] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TP_ALERT] SET RECOVERY FULL 
GO
ALTER DATABASE [TP_ALERT] SET  MULTI_USER 
GO
ALTER DATABASE [TP_ALERT] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TP_ALERT] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TP_ALERT] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TP_ALERT] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TP_ALERT] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'TP_ALERT', N'ON'
GO
ALTER DATABASE [TP_ALERT] SET QUERY_STORE = OFF
GO
USE [TP_ALERT]
GO
USE [TP_ALERT]
GO
/****** Object:  Sequence [dbo].[ALERT_CONFIG_SEQ]    Script Date: 2020/11/8 下午 04:01:07 ******/
CREATE SEQUENCE [dbo].[ALERT_CONFIG_SEQ] 
 AS [bigint]
 START WITH 3
 INCREMENT BY 1
 MINVALUE -9223372036854775808
 MAXVALUE 9223372036854775807
 CACHE 
GO
USE [TP_ALERT]
GO
/****** Object:  Sequence [dbo].[ALERT_LOG_SEQ]    Script Date: 2020/11/8 下午 04:01:07 ******/
CREATE SEQUENCE [dbo].[ALERT_LOG_SEQ] 
 AS [bigint]
 START WITH 1
 INCREMENT BY 1
 MINVALUE -9223372036854775808
 MAXVALUE 9223372036854775807
 CACHE 
GO
USE [TP_ALERT]
GO
/****** Object:  Sequence [dbo].[HR_CALENDAR_SEQ]    Script Date: 2020/11/8 下午 04:01:07 ******/
CREATE SEQUENCE [dbo].[HR_CALENDAR_SEQ] 
 AS [int]
 START WITH 1
 INCREMENT BY 1
 MINVALUE -2147483648
 MAXVALUE 2147483647
 NO CACHE 
GO
/****** Object:  Table [dbo].[ALERT_CONFIG]    Script Date: 2020/11/8 下午 04:01:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ALERT_CONFIG](
	[SID] [int] NOT NULL,
	[MODE] [char](1) NOT NULL,
	[DATA_TYPE] [varchar](50) NOT NULL,
	[LOCATION] [varchar](4) NOT NULL,
	[DEVICE_ID] [varchar](4) NOT NULL,
	[DATA_FIELD] [varchar](50) NOT NULL,
	[MAX_VALUE] [real] NOT NULL,
	[MIN_VALUE] [real] NOT NULL,
	[CHECK_INTERVAL] [int] NOT NULL,
	[ALERT_INTERVAL] [int] NULL,
	[SUN] [bit] NULL,
	[SUN_STIME] [time](0) NULL,
	[SUN_ETIME] [time](0) NULL,
	[MON] [bit] NULL,
	[MON_STIME] [time](0) NULL,
	[MON_ETIME] [time](0) NULL,
	[TUE] [bit] NULL,
	[TUE_STIME] [time](0) NULL,
	[TUE_ETIME] [time](0) NULL,
	[WED] [bit] NULL,
	[WED_STIME] [time](0) NULL,
	[WED_ETIME] [time](0) NULL,
	[THU] [bit] NULL,
	[THU_STIME] [time](0) NULL,
	[THU_ETIME] [time](0) NULL,
	[FRI] [bit] NULL,
	[FRI_STIME] [time](0) NULL,
	[FRI_ETIME] [time](0) NULL,
	[STA] [bit] NULL,
	[STA_STIME] [time](0) NULL,
	[STA_ETIME] [time](0) NULL,
	[CHECK_DATE] [smalldatetime] NULL,
	[ALERT_DATE] [smalldatetime] NULL,
	[MAIL_TO] [varchar](8000) NULL,
	[CHECK_HR_CALENDAR] [bit] NULL,
	[CDATE] [datetime2](0) NULL,
	[CUSER] [varchar](50) NULL,
	[MDATE] [datetime2](0) NULL,
	[MUSER] [varchar](50) NULL,
 CONSTRAINT [PK_ALERT_CONFIG] PRIMARY KEY CLUSTERED 
(
	[SID] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ALERT_LOG]    Script Date: 2020/11/8 下午 04:01:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ALERT_LOG](
	[SID] [bigint] NOT NULL,
	[DATA_TYPE] [varchar](50) NOT NULL,
	[LOCATION] [varchar](4) NOT NULL,
	[DEVICE_ID] [varchar](4) NOT NULL,
	[DATA_FIELD] [varchar](50) NOT NULL,
	[MAX_VALUE] [real] NOT NULL,
	[MIN_VALUE] [real] NOT NULL,
	[ALERT_VALUE] [real] NULL,
	[CHECK_DATE] [datetime2](0) NOT NULL,
 CONSTRAINT [PK_ALERT_LOG] PRIMARY KEY CLUSTERED 
(
	[SID] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HR_CALENDAR]    Script Date: 2020/11/8 下午 04:01:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HR_CALENDAR](
	[SN] [int] NOT NULL,
	[HR_DATE] [date] NOT NULL,
	[DATE_TYPE] [char](1) NOT NULL,
	[MEMO] [varchar](500) NULL,
	[CDATE] [datetime2](0) NOT NULL,
	[CUSER] [varchar](50) NOT NULL,
	[MDATE] [datetime2](0) NOT NULL,
	[MUSER] [varchar](50) NOT NULL,
 CONSTRAINT [PK_HR_CALENDAR] PRIMARY KEY CLUSTERED 
(
	[SN] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UK_HR_CALENDAR_HR_DATE] UNIQUE NONCLUSTERED 
(
	[HR_DATE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UK_ALERT_CONFIG]    Script Date: 2020/11/8 下午 04:01:08 ******/
CREATE NONCLUSTERED INDEX [UK_ALERT_CONFIG] ON [dbo].[ALERT_CONFIG]
(
	[DATA_TYPE] ASC,
	[LOCATION] ASC,
	[DEVICE_ID] ASC,
	[DATA_FIELD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_ALERT_LOG_CHECK_DATE]    Script Date: 2020/11/8 下午 04:01:08 ******/
CREATE NONCLUSTERED INDEX [IX_ALERT_LOG_CHECK_DATE] ON [dbo].[ALERT_LOG]
(
	[CHECK_DATE] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_ALERT_LOG_DATA_TYPE_LOCATION_DEVICE_ID]    Script Date: 2020/11/8 下午 04:01:08 ******/
CREATE NONCLUSTERED INDEX [IX_ALERT_LOG_DATA_TYPE_LOCATION_DEVICE_ID] ON [dbo].[ALERT_LOG]
(
	[DATA_TYPE] ASC,
	[LOCATION] ASC,
	[DEVICE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [TP_ALERT] SET  READ_WRITE 
GO
