USE [TP_DSCCR]

ALTER TABLE [dbo].[AHU] ALTER COLUMN [LOCATION] VARCHAR(50) NOT NULL;
ALTER TABLE [dbo].[AHU] ALTER COLUMN [DEVICE_ID] VARCHAR(50) NOT NULL;

ALTER TABLE [dbo].[Chiller] ALTER COLUMN [LOCATION] VARCHAR(50) NOT NULL;
ALTER TABLE [dbo].[Chiller] ALTER COLUMN [DEVICE_ID] VARCHAR(50) NOT NULL;

ALTER TABLE [dbo].[COP] ALTER COLUMN [LOCATION] VARCHAR(50) NOT NULL;
ALTER TABLE [dbo].[COP] ALTER COLUMN [DEVICE_ID] VARCHAR(50) NOT NULL;

ALTER TABLE [dbo].[CP] ALTER COLUMN [LOCATION] VARCHAR(50) NOT NULL;
ALTER TABLE [dbo].[CP] ALTER COLUMN [DEVICE_ID] VARCHAR(50) NOT NULL;

ALTER TABLE [dbo].[CT] ALTER COLUMN [LOCATION] VARCHAR(50) NOT NULL;
ALTER TABLE [dbo].[CT] ALTER COLUMN [DEVICE_ID] VARCHAR(50) NOT NULL;

ALTER TABLE [dbo].[ZP1] ALTER COLUMN [LOCATION] VARCHAR(50) NOT NULL;
ALTER TABLE [dbo].[ZP1] ALTER COLUMN [DEVICE_ID] VARCHAR(50) NOT NULL;

ALTER TABLE [dbo].[RRS_PVOI] ALTER COLUMN [LOCATION] VARCHAR(50) NOT NULL;
ALTER TABLE [dbo].[RRS_PVOI] ALTER COLUMN [DEVICE_ID] VARCHAR(50) NOT NULL;

ALTER TABLE [dbo].[RRS_PWLS] ALTER COLUMN [LOCATION] VARCHAR(50) NOT NULL;
ALTER TABLE [dbo].[RRS_PWLS] ALTER COLUMN [DEVICE_ID] VARCHAR(50) NOT NULL;

ALTER TABLE [dbo].[RRS_VFLH] ALTER COLUMN [LOCATION] VARCHAR(50) NOT NULL;
ALTER TABLE [dbo].[RRS_VFLH] ALTER COLUMN [DEVICE_ID] VARCHAR(50) NOT NULL;

ALTER TABLE [dbo].[WSDS_PVOI] ALTER COLUMN [LOCATION] VARCHAR(50) NOT NULL;
ALTER TABLE [dbo].[WSDS_PVOI] ALTER COLUMN [DEVICE_ID] VARCHAR(50) NOT NULL;

ALTER TABLE [dbo].[WSDS_PWLS] ALTER COLUMN [LOCATION] VARCHAR(50) NOT NULL;
ALTER TABLE [dbo].[WSDS_PWLS] ALTER COLUMN [DEVICE_ID] VARCHAR(50) NOT NULL;